DROP TABLE IF EXISTS ACCOUNT, SYMBOL, SORDER, BORDER;
CREATE TABLE ACCOUNT(           
  ID   INT PRIMARY KEY  NOT NULL, 
  BALANCE        INT             NOT NULL );
CREATE TABLE SYMBOL(
  SYM   TEXT   NOT NULL, 
  ID    INT              NOT NULL,
  POS        INT             NOT NULL,
  primary key(SYM, ID));
CREATE TABLE SORDER(
  order_num    SERIAL PRIMARY KEY NOT NULL,	
  SYM   TEXT   NOT NULL, 
  ID    INT            NOT NULL,
  PRICE INT   NOT NULL,
  AMOUNT        INT             NOT NULL );
CREATE TABLE BORDER(
   order_num    SERIAL PRIMARY KEY  NOT NULL,  
   SYM   TEXT  NOT NULL, 
   ID    INT            NOT NULL,
   PRICE INT   NOT NULL,
   AMOUNT        INT             NOT NULL );
ALTER TABLE SYMBOL ADD CONSTRAINT fk_symbol_ID_foreign_account FOREIGN KEY(ID) REFERENCES ACCOUNT(ID)ON UPDATE CASCADE;
ALTER TABLE SORDER ADD CONSTRAINT fk_sorder_ID_foreign_account FOREIGN KEY(ID) REFERENCES ACCOUNT(ID)ON UPDATE CASCADE;
ALTER TABLE BORDER ADD CONSTRAINT fk_border_ID_foreign_account FOREIGN KEY(ID) REFERENCES ACCOUNT(ID)ON UPDATE CASCADE;


