CREATE TABLE ACCOUNT(           
  ID   INT PRIMARY KEY  NOT NULL, 
  BALANCE        INT             NOT NULL );
CREATE TABLE SYMBOL(
  SYM   TEXT   NOT NULL, 
  ID    INT    REFERENCES ACCOUNT(ID),
  POS   INT             NOT NULL,
  primary key(SYM, ID));
CREATE TABLE TORDER(
  ID   	INT PRIMARY KEY NOT NULL,
  ACCOUNT INT REFERENCES ACCOUNT(ID),
  SYM   TEXT   NOT NULL,
  PRICE INT   NOT NULL,
  AMOUNT        INT    NOT NULL,
  order by price desc);
CREATE TABLE EXCUTED(
  ID INT NOT NULL,
  ACCOUNT INT REFERENCES ACCOUNT(ID),
  SYM TEXT NOT NULL,
  PRICE INT NOT NULL,
  AMOUNT INT NOT NULL,
  Epoch BIGINT NOT NULL);
  	 
CREATE TABLE CANCELED(
  ID INT NOT NULL,
  ACCOUNT INT REFERENCES ACCOUNT(ID),
  SYM TEXT NOT NULL,
  PRICE INT NOT NULL,
  AMOUNT INT NOT NULL,
  Epoch BIGINT NOT NULL	);


