DROP TABLE IF EXISTS ACCOUNT, SYMBOL, SORDER, BORDER;
CREATE TABLE ACCOUNT(           
  ID   INT PRIMARY KEY  NOT NULL, 
  BALANCE        INT             NOT NULL );
CREATE TABLE SYMBOL(
  SYM   TEXT   NOT NULL, 
  ID    INT    REFERENCES ACCOUNT(ID),
  POS   INT             NOT NULL,
  primary key(SYM, ID));
CREATE TABLE TORDER(
  ID   	SERIAL PRIMARY KEY NOT NULL;
  SYM   TEXT   NOT NULL,
  ID    INT            NOT NULL,
  PRICE INT   NOT NULL,
  AMOUNT        INT             NOT NULL );
  

ALTER TABLE SYMBOL ADD CONSTRAINT fk_symbol_ID_foreign_account FOREIGN KEY(ID) REFERENCES ACCOUNT(ID)ON UPDATE CASCADE;


